# Generated by Django 3.2.3 on 2021-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pages', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
