# Generated by Django 3.1.3 on 2021-05-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0004_auto_20210528_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='book',
            name='is_liked',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
