# Generated by Django 3.2.3 on 2021-06-03 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_database', '0007_auto_20210603_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book_liked',
        ),
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='books_liked_by_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
