# Generated by Django 3.2.3 on 2021-06-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0008_auto_20210603_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
    ]
