# Generated by Django 3.2.3 on 2021-06-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0012_alter_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
